name: speakerdiart
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg<4.4
  - portaudio=19.6.*
  - libsndfile>=1.2.2
  - pip
  - pip:
    - faster-whisper>=1.0,<2.0
    - diart>=0.9,<1.1
    - onnxruntime>=1.17,<2.0
    - openai>=1.0,<2.0
    - pytest>=7.0,<9.0
    - tkinter